config/routes.rb
Rails.application.routes.draw do
  resources :account_activations, only: [:edit]
  resources :microposts, only: [:create, :destroy]

  root 'static_pages#home'
  get 'users/show'
  get 'static_pages/home'
  get 'static_pages/help'

  get '/signup',  to: 'users#signup'
  get '/login', to: 'sessions#signin'
  post '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users do
    member do
      get :following, :followers
    end
  end
  resources :relationships, only: [:create, :destroy]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/micropost.rb
class Micropost < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :content, presence: true, length: {maximum: 255}
  default_scope -> {order(created_at: :desc)}

end

app/models/relationship.rb
class Relationship < ApplicationRecord
	belongs_to :follower, class_name: "User"
  	belongs_to :followed, class_name: "User"
  	validates :follower_id, presence: true
  	validates :followed_id, presence: true 
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :remember_token
  has_many :microposts, dependent: :destroy
  has_many :active_relationships, class_name:  "Relationship",
                                  foreign_key: "follower_id",
                                  dependent:   :destroy
  has_many :following, through: :active_relationships, source: :followed

  has_many :passive_relationships, class_name: "Relationship",
                                   foreign_key: "followed_id",
                                   dependent: :destroy

  has_many :followers, through: :passive_relationships, source: :follower

  before_save { self.email = email.downcase }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
                    format: { with: VALID_EMAIL_REGEX },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  # Returns the hash digest of the given string.
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  def remember
  	self.remember_token = User.new_token
  	update_attribute(:remember_digest, User.digest(remember_token))
  end

  def authenticated?(remember_token)
  	return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  def forget
    update_attribute(:remember_digest, nil)
  end


  def feed
    following_ids = "SELECT followed_id FROM relationships
                     WHERE  follower_id = :user_id"
    Micropost.where("user_id IN (#{following_ids})
                     OR user_id = :user_id", user_id: id)
  end

  def follow(other_user)
    self.following << other_user
  end

  def unfollow(other_user)
    self.following.delete(other_user)
  end

  def following?(other_user)
    self.following.include?(other_user)
  end

end

app/controllers/account_activations_controller.rb
class AccountActivationsController < ApplicationController
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/microposts_controller.rb
class MicropostsController < ApplicationController
	before_action :logged_in_user, only: [:create, :destroy]
	before_action :correct_user, only: [:destroy]

	def create
		if logged_in_user
			@micropost = logged_in_user.microposts.build(micropost_params)
			if @micropost.save
				redirect_to root_url
			else
				@feed_items = []
				render 'static_pages/home'
			end
		end
	end

	def destroy
		correct_user.destroy
		redirect_to request.referrer || root_url
	end

	def correct_user
		@micropost = logged_in_user.microposts.find_by(id: params[:id])
		if @micropost.nil?
			redirect_to root_url
		else
			return @micropost
		end
	end

	private
		def micropost_params
			params.require(:micropost).permit(:content)
		end

end

app/controllers/relationships_controller.rb
class RelationshipsController < ApplicationController

def create 
	@user = User.find_by(id: params[:followed_id])
	logged_in_user.follow(@user)
	respond_to do |format|
		format.html {redirect_to @user}
		format.js
	end
end

def destroy
	@user = Relationship.find(params[:id]).followed
    logged_in_user.unfollow(@user)
    respond_to do |format|
      format.html { redirect_to @user }
      format.js
    end
end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def signin
  end

  def create 
  	user = User.find_by(email:params[:session][:email].downcase)
  	if user && user.authenticate(params[:session][:password])
  		log_in user
      current_user
  		redirect_to user
  	else
  		render 'signin'
  	end
  end

  def destroy
  	if log_in?
  		log_out
  		redirect_to root_path
  	end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in_user
  		@micropost = logged_in_user.microposts.build
  		@feed_items = logged_in_user.feed.paginate(page: params[:page])
  	end
  end

  def help
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:index, :edit, :update, :destroy,
                                        :following, :followers]

  def welcome
    render html: "welcome to app"
  end

  def index
  	@users = User.paginate(page: params[:page])
  end

  def show
    @user = User.find(params[:id])
    # unless logged_in @user
    #   redirect_to login_path
    # else
      @microposts = @user.microposts.paginate(page: params[:page])
    # end
  end

  def signup
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
  		redirect_to @user
  	else
  		render 'signup'
  	end
  end

  def following
    @title = "Following"
    @user  = User.find(params[:id])
    @users = @user.following.paginate(page: params[:page])
    render 'show_follow'
  end

  def followers
    @title = "Followers"
    @user  = User.find(params[:id])
    @users = @user.followers.paginate(page: params[:page])
    render 'show_follow'
  end

  private
  	def user_params
  		params.require(:user).permit(:name, :email, :password, :password_confirmation);
  	end
end

app/helpers/account_activations_helper.rb
module AccountActivationsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/microposts_helper.rb
module MicropostsHelper
end

app/helpers/relationships_helper.rb
module RelationshipsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
	def log_in(user)
		session[:user_id] = user.id
	end

	def log_out
		forget(current_user)
		session.delete(:user_id)
		@current_user = nil
	end
	
	def current_user
	    if (user_id = session[:user_id])
	      @current_user ||= User.find_by(id: user_id)
	    elsif (user_id = cookies.signed[:user_id])
	      user = User.find_by(id: user_id)
	      if user && user.authenticated?(cookies[:remember_token])
	        log_in user
	        @current_user = user
	      end
	    end
  	end

	def logged_in(user)
		if(user.id == session[:user_id])
			true
		else
			false
		end
	end

	def remember(user)
	    user.remember
	    cookies.permanent.signed[:user_id] = user.id
	    cookies.permanent[:remember_token] = user.remember_token
  	end

  	def forget
  		user.forget
  		cookies.delete(:user_id)
    	cookies.delete(:remember_token)
  	end

  	def logged_in_user
  		User.find_by(id: session[:user_id])
  	end

  	def logged_in?
  		!logged_in_user.nil?
  	end

  	def current_user?(user)
  		temp_user = logged_in_user
  		if temp_user.nil?
  			return false
  		elsif temp_user.id == user.id
  			return true
  		else 
  			return false
  		end
  	end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper

  # Returns the Gravatar for the given user.
  def gravatar_for(user,size)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.name, class: "gravatar")
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>App</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/microposts/_micropost.html.erb
<li id="micropost-<%= micropost.id %>">
  <%= link_to gravatar_for(micropost.user, size: 50), micropost.user %>
  <span class="user"><%= link_to micropost.user.name, micropost.user %></span>
  <span class="content"><%= micropost.content %></span>
  <span class="timestamp">
    Posted <%= time_ago_in_words(micropost.created_at) %> ago.
  </span>
  <%= link_to "Delete", micropost, method: :delete,
  								  data: {confirm: "You sure?"} %>
</li>

app/views/relationships/create.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/unfollow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/relationships/destroy.js.erb
$("#follow_form").html("<%= escape_javascript(render('users/follow')) %>");
$("#followers").html('<%= @user.followers.count %>');

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(object.errors.count, "error") %>.
    </div>
    <ul>
    <% object.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
<% end %>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost) do |f| %>
  <%= render 'shared/error_messages', object: f.object %>
  <div class="field">
    <%= f.text_area :content, placeholder: "Compose new micropost..." %>
  </div>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>

app/views/shared/_stats.html.erb
<% @user ||= logged_in_user %>
<div class="stats">
  <a href="<%= following_user_path(@user) %>">
    <strong id="following" class="stat">
      <%= @user.following.count %>
    </strong>
    following
  </a>
  <a href="<%= followers_user_path(@user) %>">
    <strong id="followers" class="stat">
      <%= @user.followers.count %>
    </strong>
    followers
  </a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(logged_in_user, size: 50), logged_in_user %>
<h1><%= logged_in_user.name %></h1>
<span><%= link_to "view my profile", logged_in_user %></span>
<span><%= pluralize(logged_in_user.microposts.count, "micropost") %></span>

app/views/shared/error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/help.html.erb
<h1>Help</h1>
<p>
  Get help on the Ruby on Rails Tutorial at the
  <a href="http://www.railstutorial.org/help">Rails Tutorial help page</a>.
  To get help on this sample app, see the
  <a href="http://www.railstutorial.org/book"><em>Ruby on Rails Tutorial</em>
  book</a>.
</p>

app/views/static_pages/home.html.erb
<% if logged_in_user %>
  <div class="row">
    <aside class="col-md-4">
		<section class="user_info">
			<%= render 'shared/user_info' %>
		</section>
		<section class="micropost_form">
			<%= render 'shared/micropost_form' %>
		</section>
    <section class="stats">
        <%= render 'shared/stats' %>
      </section>
    </aside>
    <div class="col-md-8">
      <h3>Micropost Feed</h3>
      <%= render 'shared/feed' %>
    </div>
  </div>
<% else %>
  <div class="center jumbotron">
    <h1>Welcome to the Sample App</h1>
    <h2>
      This is the home page for the
      <a href="http://www.railstutorial.org/">Ruby on Rails Tutorial</a>
      sample application.
    </h2>
    <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
    <h2>Existing User?</h2>
    <%= link_to "Sign In", login_path, class: "btn btn-lg btn-primary" %>
  </div>
<% end %>

app/views/users/_follow.html.erb
<%= form_for(logged_in_user.active_relationships.build, remote: true) do |f| %>
  <div><%= hidden_field_tag :followed_id, @user.id %></div>
  <%= f.submit "Follow", class: "btn btn-primary" %>
<% end %>

app/views/users/_follow_form.html.erb
<% unless current_user?(@user) %>
  <div id="follow_form">
  <% if logged_in_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_unfollow.html.erb
<%= form_for(current_user.active_relationships.find_by(followed_id: @user.id),
             html: { method: :delete }, remote: true) do |f| %>
  <%= f.submit "Unfollow", class: "btn" %>
<% end %>

app/views/users/_user.html.erb
<li>
  <%= gravatar_for user, size: 50 %>
  <%= link_to user.name, user %>
</li>

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>

<%= will_paginate %>

<ul class="users">
  <%= render @users %>
</ul>

<%= will_paginate %>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<div class="row">
  <aside class="col-md-4">
    <section class="user_info">
      <h1>
        <%= gravatar_for @user, size: 50 %>
        <%= @user.name %>
      </h1>
    </section>
    <section class="stats">
      <%= render 'shared/stats' %>
    </section>
  </aside>
  <div class="col-md-8">
  <%= render 'follow_form' if logged_in? %>
    <% if @user.microposts.any? %>
      <h3>Microposts (<%= @user.microposts.count %>)</h3>
      <ol class="microposts">
        <%= render @microposts %>
      </ol>
      <%= will_paginate @microposts %>
    <% end %>
  </div>
</div>

app/views/users/signup.html.erb
<% provide(:title, 'Sign up') %>
<h1>Sign up</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user) do |f| %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :email %>
      <%= f.email_field :email %>

      <%= f.label :password %>
      <%= f.password_field :password %>

      <%= f.label :password_confirmation, "Confirmation" %>
      <%= f.password_field :password_confirmation %>

      <%= f.submit "Create my account", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>